[project]
name = "meta-threads-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.0.9",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
