name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.11.5 black==25.1.0 mypy==1.15.0
          pip install -e .
      
      - name: Lint with Ruff
        run: |
          ruff check --fix .
      
      - name: Format with Ruff
        run: |
          ruff format .
      
      - name: Format with Black
        run: |
          black .
      
      - name: Type check with MyPy
        run: |
          mypy .
